// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPQtPytnD20nrWmQPuPqKGI5TRn_y4K5A',
    appId: '1:257975546672:web:eb858f983805997a21cef5',
    messagingSenderId: '257975546672',
    projectId: 'bicaraai',
    authDomain: 'bicaraai.firebaseapp.com',
    storageBucket: 'bicaraai.appspot.com',
    measurementId: 'G-L1WP9KMQQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC59sjjgZF4EZcm5TV-C187pz4MY3OzqAc',
    appId: '1:257975546672:android:041741b85a76a21721cef5',
    messagingSenderId: '257975546672',
    projectId: 'bicaraai',
    storageBucket: 'bicaraai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXbW0YgT_3cXRtkZVq7Gb92LnpvFKdDZ0',
    appId: '1:257975546672:ios:4aaf6b313312319821cef5',
    messagingSenderId: '257975546672',
    projectId: 'bicaraai',
    storageBucket: 'bicaraai.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXbW0YgT_3cXRtkZVq7Gb92LnpvFKdDZ0',
    appId: '1:257975546672:ios:9e65b044fa9f4e8121cef5',
    messagingSenderId: '257975546672',
    projectId: 'bicaraai',
    storageBucket: 'bicaraai.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
